language: go

env:
  matrix:
  - GO111MODULE=on

go:
  - '1.13'


script:
  - make test
  - make build

before_deploy:
  - make build

deploy:
  provider: releases
  api_key:
    secure: "A9MErQ2j34Cnl1XyabRkZKXn738OkLb1XT8HMQ0kxSxgin2UaDBKvHAhp/bpFozzTAuc7dftLs2cRBnH6UER9GxRkFWdfh7n2T41WIeLi0LJ2CH20FwDGIkfHAiLmaa4DbRW99BfaIJhZ9+kbQcuB4a4AfvtFPKV8VUn20PFvNKOMSz9vJdf5bq+Stm0gcbDbic/dukHngpbpJHjC+se6Q3v/z88J6/0i4+lrg88VkubJxa4xHm/l5j6exQCDRVZeeXGXYT8lVyRFWpqIsur0gKMwODaBTqkmE6c7G/c8ToJdsCWdf/tarmi6n3VSvkOYFvOd6vDMn3jvZpcZCCKSqRQVPJ0ujRgrRKhjVMpcFUCn9yGIB0LLFGuEQItw47D2bnDRIygWM0o3nq2EuPgUkzRECFUCt0Dwm1jLE0p/O72wofFO2oBsRY+PlX4oQ7NhVG3JPCrIfumFdUMUNBHpG/JMpya+wxGLwjW3KZnqL2ezvpsFRsm3YJvrEHXygFgKiUKeUm457oOklBL+kIYhPMvtWKl7XgtupX57rEfpLYbRedO3dBKQ0Osst5m94DYiNBbRvnKKcWjYcq0vv02J1hypx2p8xY1/ps6DgbqrWoA67LPY+vp7Reh6iJjAJqoPWuU+FiS48UwP6hjU0A3OD4BBX1tYt9ohAmNWahc0Ac="
  file:
    - "./ancientt"
  skip_cleanup: true
  on:
    tags: true

