language: go

env:
  matrix:
  - GO111MODULE=on

go:
  - '1.13'

script:
  - make test
  - make build

before_deploy:
  - make build

deploy:
  provider: releases
  api_key:
    secure: "MJELEcF4C1vMT7Il/BuRJLnWqZtB5UIIyJlzqsOLxkcbZ4ZGuPDwxTEBJoCbPgrIvHD2GuKl+aqJ/kPnVWNjxUMIomeyJ3N8w9HMD7owM4WYp2zTv6nR0p1kwPQZtQItTWu3lSmpAVjrqAMdxXq/DW1d0reCuDc3B+wUrePJIatVLWNNig3dGK+EWo2YO2D5kIUmoEaQwSbqOnTvA+iP56UmMY1FGglSX+ijx3+NT8qluEOquVbF0unA6Fl6MgXRP6QeOhn1gWiFEsf/9wjPbEn6kxXzXWCLDraLr4G1HwGr3RkJx3g0OWBUFTJFViEiMWJcNWve0xjeAtYg6oqSrmKO49jWOSZ7uhnICyCnGF4xs2wq5TrfBMOlRCKbgH9jZffgqL+gf3QCnHuaKN0ubeR2miTV7tZD+7GRzYLkbrdNf8gchIyhLKs34wO7Yhlevz9oA/R+NamdiYKFMvBGn44rFnmp+0V6dY1JspeIR78XYp1fH6/y2xvqa7AtD1rXzpeKsRhXIe4ebqAz+or8eoUsjL6HbQip5zAlJZ07a26d1RQo6262PA+DJ3z6bAWMD2Jqt3H9TR6BF2j9uajyHIhFY+0fGMH9poymLNyj5x1c6mxYg/+BL3IwkrrVluEzAG/RzqmGd6koYjkRK+ourIaY+D/YoIrGVCmo5KNACWQ="
  file:
    - "./ancientt"
  skip_cleanup: true
  on:
    tags: true

