---
- hosts: all
  remote_user: root
  tasks:
    - name: Install dependencies for Ancientt
      package: 
        name: "{{ item }}"
        state: present 
      with_items:
        - iperf3
        - procps
