---
- hosts: all
  remote_user: root
  tasks:
    - name: Host Python must be at least 3.5+
      assert:
        that: "ansible_python_version is version_compare('3.5', '>=')"
        msg: |
          pingparsing requires at least python 3.5+ on th target machines
    - name: Install dependencies for Ancientt
      package: 
        name: "{{ item }}"
        state: present 
      with_items:
        - procps
    - name: Pip install pingparsing package
      pip:
        name: pingparsing
